basic:
  clash_config_dir: ~/.local/proxy/mihomo
  clash_bin_path: /usr/bin/mihomo
  clash_config_path: ~/.local/proxy/mihomo/config.yaml
  timeout: null
service: 
  clash_srv_nam: mihomo
  is_user: false
extra:
  edit_cmd: alacritty -e nvim %s
  open_dir_cmd: alacritty -e ranger %s
