[package]
name = "clashtui"
version = "0.3.0-reborn"
edition = "2021"

authors = ["Johan Chane <johanchanex at gmail dot com>"]
description = "Mihomo TUI Client"
license = "MIT"
repository = "https://github.com/JohanChane/clashtui"
homepage = "https://github.com/JohanChane/clashtui"
documentation = "https://github.com/JohanChane/clashtui"
readme = "README.md"

exclude = [".github", ".gitignore", "PkgManagers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [badges]
# maintenance = { status = "passively-maintained" }

[features]
tui = ["ratatui", "crossterm", "tokio", "connection-tab"]
template = []
connection-tab = ["ratatui/unstable-widget-ref"]
default = ["tui"]


[dependencies]
log = "0.4.22"
clap_complete = { version = "4.5.26" }
anyhow = "1.0.86"
is-root = { version = "0.1.4" }
serde = { version = "1.0.210", features = ["derive"] }
minreq = { version = "2.12.0", features = [
  "proxy",
  "https",
  "json-using-serde",
] }
serde_json = "1.0.128"
serde_yaml = "0.9.34"
futures-util = { version = "0.3.30", default-features = false }
thiserror = "1.0.63"
bitflags = { version = "2.6.0", optional = true }

[dependencies.tokio]
version = "1.40.0"
features = ["rt", "macros", "sync", "time"]
optional = true

[dependencies.crossterm]
version = "0.28.1"
default-features = false
features = ["events", "event-stream"]
optional = true

[dependencies.ratatui]
version = "0.28.1"
default-features = false
features = ["crossterm"]
optional = true

[target.'cfg(windows)'.dependencies]
encoding_rs = "0.8.34"

[dependencies.log4rs]
version = "1.3.0"
default-features = false
features = ["pattern_encoder", "file_appender"]

[patch.crates-io]
log4rs = { git = "https://github.com/Jackhr-arch/log4rs" }
is-root = { git = "https://github.com/Jackhr-arch/is-root" }

[dependencies.clap]
version = "4.5.17"
default-features = false
features = ["std", "derive", "help", "usage", "suggestions", "color"]


[profile.release]
lto = "fat"
opt-level = 's'
strip = true
incremental = true


[package.metadata.deb]
maintainer = 'Jackhr-arch <63526062+Jackhr-arch@users.noreply.github.com>'
extended-description = """
A tool for mihomo
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
  [
    'target/release/clashtui',
    'usr/bin/clashtui',
    '755',
  ],
  [
    'README.md',
    'usr/share/doc/clashtui/README.md',
    '644',
  ],
]
maintainer-scripts = 'debian/'
