[package]
name = "clashtui"
version = "0.2.2"
edition = "2021"

authors = ["Johan Chane <johanchanex at gmail dot com>"]
description = "Mihomo TUI Client"
license = "MIT"
repository = "https://github.com/JohanChane/clashtui"
homepage = "https://github.com/JohanChane/clashtui"
documentation = "https://github.com/JohanChane/clashtui"
readme = "README.md"

include = ["clashtui/*", "LICENSE", "README.md", "README_ZH.md"]

[badges]
maintenance = { status = "passively-maintained" }

[features]
tui = ["ratatui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { version = "^0", default-features = false, features = [
  "crossterm",
], optional = true }
log = "^0.4"
enumflags2 = "^0.7.10"
clap_complete = "^4.5.7"
anyhow = "^1.0.86"
is-root =  "0.1.3"
serde = { version = "^1", features = ["derive"] }
minreq = { version = "^2", features = ["proxy", "https"] }
serde_json = "^1"
serde_yaml = "0.9"

[dependencies.crossterm]
version = "^0.27"
default-features = false
features = ["events", "windows"]


[target.'cfg(windows)'.dependencies]
encoding = "^0.2.33"

[dependencies.log4rs]
version = "^1.3"
default-features = false
features = ["pattern_encoder", "file_appender"]

[dependencies.clap]
version = "^4.5.8"
default-features = false
features = ["std", "derive", "help", "usage", "suggestions", "color"]


[workspace]
resolver = '2'

[build]
incremental = true # for ci cache

[profile.release]
lto = "fat"
opt-level = 's'
strip = true

[package.metadata.deb]
maintainer = 'Jackhr-arch <63526062+Jackhr-arch@users.noreply.github.com>'
extended-description = """
A tool for mihomo
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
  [
    'target/release/clashtui',
    'usr/bin/clashtui',
    '755',
  ],
  [
    '../README.md',
    'usr/share/doc/clashtui/README.md',
    '644',
  ],
]
maintainer-scripts = 'debian/'
